# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vocab_quiz_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(307, 252)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_japanese = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_japanese.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_japanese.setFont(font)
        self.radioButton_japanese.setObjectName("radioButton_japanese")
        self.buttonGroup_radio_language = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_radio_language.setObjectName("buttonGroup_radio_language")
        self.buttonGroup_radio_language.addButton(self.radioButton_japanese)
        self.gridLayout_2.addWidget(self.radioButton_japanese, 3, 0, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout_2.addWidget(self.pushButton_start, 4, 0, 1, 1)
        self.label_text_asnwer_language = QtWidgets.QLabel(self.centralwidget)
        self.label_text_asnwer_language.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_text_asnwer_language.setFont(font)
        self.label_text_asnwer_language.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_text_asnwer_language.setTextFormat(QtCore.Qt.PlainText)
        self.label_text_asnwer_language.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_asnwer_language.setObjectName("label_text_asnwer_language")
        self.gridLayout_2.addWidget(self.label_text_asnwer_language, 0, 0, 1, 1)
        self.radioButton_english = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_english.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_english.sizePolicy().hasHeightForWidth())
        self.radioButton_english.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_english.setFont(font)
        self.radioButton_english.setObjectName("radioButton_english")
        self.buttonGroup_radio_language.addButton(self.radioButton_english)
        self.gridLayout_2.addWidget(self.radioButton_english, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 307, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "日本語 Vocab Practice"))
        self.radioButton_japanese.setText(_translate("MainWindow", "日本語"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.label_text_asnwer_language.setText(_translate("MainWindow", "Choose What Language to Answer in:"))
        self.radioButton_english.setText(_translate("MainWindow", "English"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
